.PHONY: hello clean

help:
	@echo "Available targets:"
	@echo "  hello - Say hello"
	@echo "  clean - Remove all .txt files"
	@echo "  help  - Show this help message"

hello:
	@echo "Hello, make!!!"

clean:
	rm -f *.txt

